#!/bin/bash

cat /etc/passwd | while read line; do
    shell=$(echo $line | awk -F ":" '{print $7}')
    uid=$(echo $line | awk -F ":" '{print $3}')

    if [ $uid -ge 1000 ]; then
        echo $line | grep -v "nologin"
    fi
done