network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - 192.168.2.10/24         
      gateway4: 192.168.2.254     
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4

    eth1:
      dhcp4: yes                  

  wifis:
    wlan0:
      optional: true
      access-points:
        "angelberlanasmipadre":         
          password: "sexsexx"  
      dhcp4: yes
