<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="inmobiliaria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="agencias">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="agencia">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="email" type="xs:string" />
                                        <xs:element name="tlf" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="propietarios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="propietario">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="idpropietario" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="inmuebles">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="inmueble">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="numpisos" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="idinmueble" use="required" />
                                    <xs:attribute name="propietarioRef" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="pisos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="piso" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="descripcion" type="xs:string" />
                                        <xs:element name="tipo" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="idpiso" use="required" />
                                    <xs:attribute name="inmuebleRef" use="required" />
                                    <xs:attribute name="confort" use="required" />
                                    <xs:attribute name="fechapub" type="xs:date" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>