#!/bin/bash

mkdir backups 
cd backups
mkdir datos
mkdir sistemas
mkdir historicos
cd datos 
mkdir servidor_web_prod
mkdir servidor_erp
mkdir estacion_usuario_juan/
cd servidor_web_prod
mkdir archivos
mkdir bases_de_datos
cd ..
cd servidor_erp
mkdir datos_compartidos
mkdir documentos_fiscales
cd ..
cd estacion_usuario_juan
mkdir home
cd ..
cd ..
cd sistemas
mkdir servidor_web_prod
cd servidor_web_prod
mkdir config_os
mkdir kernel
mkdir volcado_completo
cd ..
mkdir servidor_erp
cd servidor_erp 
mkdir config_os
mkdir volcado_completo
cd ..
mkdir servidor_backup
cd servidor_backup 
mkdir scripts
cd ..
cd ..
cd historicos
mkdir fin_de_mesa
mkdir anuales
